/**
 * Error Code Definitions
 */

module.exports = {
  // General Errors
  INVALID_INPUT: "ERR_INVALID_INPUT",
  NOT_FOUND: "ERR_NOT_FOUND",
  UNAUTHORIZED: "ERR_UNAUTHORIZED",
  FORBIDDEN: "ERR_FORBIDDEN",

  // Blockchain Errors
  INVALID_ADDRESS: "ERR_INVALID_ADDRESS",
  INVALID_CHAIN: "ERR_INVALID_CHAIN",
  INSUFFICIENT_BALANCE: "ERR_INSUFFICIENT_BALANCE",
  TRANSACTION_FAILED: "ERR_TRANSACTION_FAILED",
  GAS_ESTIMATION_FAILED: "ERR_GAS_ESTIMATION_FAILED",

  // Game Errors
  HOUSE_NOT_FOUND: "ERR_HOUSE_NOT_FOUND",
  PLAYER_NOT_FOUND: "ERR_PLAYER_NOT_FOUND",
  NFT_NOT_FOUND: "ERR_NFT_NOT_FOUND",
  INVALID_HOUSE: "ERR_INVALID_HOUSE",
  INVALID_ACTION: "ERR_INVALID_ACTION",

  // Mint Errors
  MINT_DISABLED: "ERR_MINT_DISABLED",
  MINT_LIMIT_REACHED: "ERR_MINT_LIMIT_REACHED",
  INSUFFICIENT_TOKEN_BALANCE: "ERR_INSUFFICIENT_TOKEN_BALANCE",

  // Firebase Errors
  DATABASE_ERROR: "ERR_DATABASE_ERROR",
  FIRESTORE_ERROR: "ERR_FIRESTORE_ERROR",

  // Farcaster Errors
  INVALID_FID: "ERR_INVALID_FID",
  INVALID_SIGNATURE: "ERR_INVALID_SIGNATURE",

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: "ERR_RATE_LIMIT_EXCEEDED",
};
