#!/bin/bash

# DragNPuff Deployment Helper Menu
# Run: bash scripts/menu.sh

clear

echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                    🐉 DragNPuff Deployment Menu 🐉               ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Network: Base Mainnet (8453)"
echo "Account: cryptonique0"
echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                        SETUP COMMANDS                              ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "  [1] Create .env file from template"
echo "      cp .env.template .env"
echo ""
echo "  [2] Compile contracts"
echo "      npm run compile"
echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                      DEPLOYMENT COMMANDS                           ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "  [3] Deploy to Base Mainnet"
echo "      npm run deploy"
echo ""
echo "  [4] Deploy to Local Hardhat"
echo "      npm run deploy:local"
echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                      INTERACTION COMMANDS                          ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "  [5] Read all contract states"
echo "      npm run read-state"
echo ""
echo "  [6] Test contract connection"
echo "      npm run interact"
echo ""
echo "  [7] Mint an NFT"
echo "      npm run mint"
echo ""
echo "  [8] Execute custom functions"
echo "      npm run execute"
echo ""
echo "  [9] View comprehensive examples"
echo "      npx hardhat run scripts/examples.js --network base"
echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                       LOCAL DEVELOPMENT                            ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "  [10] Start local blockchain (terminal 1)"
echo "       npm run dev"
echo ""
echo "  [11] Execute on local blockchain (terminal 2)"
echo "       npm run execute:local"
echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                        UTILITY COMMANDS                            ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "  [12] Run tests"
echo "      npm run test"
echo ""
echo "  [13] Lint code"
echo "      npm run lint"
echo ""
echo "  [14] Format code"
echo "      npm run format"
echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                      DOCUMENTATION                                 ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "  [Q] Quick Start Guide"
echo "      cat QUICKSTART.md"
echo ""
echo "  [D] Detailed Deployment Guide"
echo "      cat DEPLOYMENT.md"
echo ""
echo "  [S] Summary of Setup"
echo "      cat SUMMARY.md"
echo ""
echo "  [R] Scripts Documentation"
echo "      cat scripts/README.md"
echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                                                                    ║"
echo "║  Contract Addresses:                                               ║"
echo "║  • DragNPuff:     0x5eCbc3931C78169cbF682C9b15602EB8f9A42387    ║"
echo "║  • FairToken:     0xC4163b96b1c45e4A8920Cb3Db822b485d9748746   ║"
echo "║  • ERC721Minter:  0x1dfA9A1afe793882229111Df790B09155EDF86e0   ║"
echo "║  • Airdrop:       0xEBD66a0624e758Ec0FA3268e012Bab33e8247080   ║"
echo "║                                                                    ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "📚 Quick Start:"
echo "  1. cp .env.template .env          (create .env file)"
echo "  2. npm run compile                 (compile contracts)"
echo "  3. npm run deploy                  (deploy to Base)"
echo "  4. npm run mint                    (mint an NFT)"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
