#!/bin/bash
# Quick Reference for DragNPuff Contract Interaction

echo "🚀 DragNPuff Contract Management"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📋 Available Scripts:"
echo ""
echo "  Development (Local Hardhat):"
echo "    npm run dev              → Start local blockchain"
echo "    npm run deploy:local     → Deploy to local hardhat"
echo "    npm run execute:local    → Run contract functions locally"
echo ""
echo "  Base Mainnet (Production):"
echo "    npm run deploy           → Deploy all 4 contracts to Base"
echo "    npm run read-state       → Check all contract states"
echo "    npm run interact         → Test contract connection"
echo "    npm run mint             → Mint an NFT"
echo "    npm run execute          → Execute custom functions"
echo ""
echo "  Utilities:"
echo "    npm run compile          → Compile contracts"
echo "    npm run test             → Run tests"
echo "    npm run lint             → Lint code"
echo "    npm run format           → Format code"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📌 Deployed Addresses (Base Mainnet):"
echo ""
echo "  DragNPuff (ERC721):"
echo "    0x5eCbc3931C78169cbF682C9b15602EB8f9A42387"
echo ""
echo "  FairToken (ERC20):"
echo "    0xC4163b96b1c45e4A8920Cb3Db822b485d9748746"
echo ""
echo "  ERC721Minter:"
echo "    0x1dfA9A1afe793882229111Df790B09155EDF86e0"
echo ""
echo "  Airdrop:"
echo "    0xEBD66a0624e758Ec0FA3268e012Bab33e8247080"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🔑 Setup Instructions:"
echo ""
echo "  1. Create .env file with:"
echo "     PRIVATE_KEY=your_private_key_here"
echo "     BASE_RPC_URL=https://mainnet.base.org"
echo ""
echo "  2. Compile contracts:"
echo "     npm run compile"
echo ""
echo "  3. Check deployment:"
echo "     npm run read-state"
echo ""
echo "  4. Mint an NFT:"
echo "     npm run mint"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📚 Documentation:"
echo "  See DEPLOYMENT.md for detailed usage guide"
echo ""
